version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00" # (UTC)
    labels:
      - "dependabot"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00" # (UTC)
    labels:
      - "dependabot"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00" # (UTC)
    labels:
      - "dependabot"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
