on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun run deploy.ts
